name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Build Spider project
        run: |
          cd apps/spider
          pnpm build

      # - name: Build Server projects
      #   run: |
      #     cd apps/server
      #     pnpm build

      - name: 创建部署目录
        run: |
          mkdir -p deploy
          cp -r apps/spider/dist deploy/apps/spider/
          cp apps/spider/package.json deploy/apps/spider/
          cp apps/spider/ecosystem.config.js deploy/apps/spider/
          cp apps/spider/pnpm-lock.yaml deploy/apps/spider/

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO'
          SOURCE: 'deploy/'
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/game-rank-spider'
          EXCLUDE: '/node_modules/'
          SCRIPT_AFTER: |
            cd /www/wwwroot/game-rank-spider/apps/spider
            pnpm install --prod
            npm run pm2:restart
